version: 2.1

jobs:
  pyenv:
    machine: true
    resource_class: kelvintaywl-cci/ec2-linux2023-tf
    environment:
    steps:
      - run:
          name: set env vars via BASH_ENV
          command: |
            echo "export PYENV_ROOT='/home/circleci/.pyenv'" >> $BASH_ENV
            echo "export PATH='/home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:$PATH'" >>  $BASH_ENV
      - run: which pyenv && python --version

workflows:
  main:
    jobs:
      - pyenv
