version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    docker:
      - image: ubuntu:22.04
    resource_class: large
    steps:
      - run: apt-get -y update
      - run: apt-get -y install curl unzip groff less tar coreutils
      - run: gpg --keyserver keyserver.ubuntu.com --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
      - ruby/install:
          # trying to install EoL'ed Ruby 2.6.10 on an Ubuntu 20.04 now
          # based on: https://github.com/rvm/rvm/issues/5254#issuecomment-1259479336
          version: '2.6.10'

workflows:
  main:
    jobs:
      - test
