version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/machine3-linux-tf
  circleci:
    machine:
      image: ubuntu-2204:2024.05.1
jobs:
  machinerunner3:
    executor: machine3-linux
    steps:
      - run: whoami
  machinecircleci:
    executor: circleci
    steps:
      - run: whoami

workflows:
  main:
    jobs:
      - machinecircleci:
          context:
            - foo-2
      - machinerunner3:
          context:
            - foo-2
