version: 2.1

jobs:
  test:
    machine: true
    resource_class: kelvintaywl-cci/machine3-windows-tf
    shell: 'powershell.exe -ExecutionPolicy Bypass'
    steps:
      - run: Write-Host "hello"

workflows:
  main:
    jobs:
      - test
