version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    machine: true
    resource_class: kelvintaywl-cci/machine3-ec2-linux2023-tf
    steps:
      - ruby/install:
          # version: '2.7.8'
          version: '2.6.10'

workflows:
  main:
    jobs:
      - test
