version: 2.1

jobs:
  test:
    docker:
      - image: cimg/base:current
    resource_class: kelvintaywl-cci/container-k3s-tf
    steps:
      - run: pwd
      - checkout

workflows:
  main:
    jobs:
      - test
