version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/lightsail-medium

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: whoami
      - run: apt-get install -y cowsay
      - run: cowsay -f tux "We love Linux!"

workflows:
  main:
    jobs:
      - foo:
          context:
            - foo-2
