version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/machine3-linux-tf

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: whoami
      - run: printenv PATH
      - run: which goenv
      - run: goenv --help
      - run: goenv install 1.6.2
      - run: goenv global 1.6.2
      - run: goenv exec go version

workflows:
  main:
    jobs:
      - foo
