version: 2.1

jobs:
  pyenv:
    machine: true
    resource_class: kelvintaywl-cci/ec2-linux2023-tf
    environment:
    steps:
      - run:
          name: set env vars via BASH_ENV
          command: |
            echo 'export FOOBAR=fizzbuzz' >> ~/.profile
            # verify
            cat $HOME/.profile

            # add to BASH_ENV file
            echo "source $HOME/.profile" >> $BASH_ENV
      - run:
          name: inspect
          command: |
            # should print fizzbuzz
            printenv FOOBAR

workflows:
  main:
    jobs:
      - pyenv
