version: 2.1

jobs:
  pyenv:
    machine: true
    resource_class: kelvintaywl-cci/ec2-linux2023-tf
    environment:
      PYENV_ROOT: '/home/circleci/.pyenv'
      PATH: '/home/circleci/.pyenv/shims:/home/circleci/.pyenv/bin:$PATH'
    steps:
      - run: which python && python --version

workflows:
  main:
    jobs:
      - pyenv
