version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/machine3-linux-tf

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: printenv FOOBAR

workflows:
  main:
    jobs:
      - foo
