version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/lightsail-medium

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: whoami
      # working directory != /tmp/dummy
      - run: pwd
      - run: df -h
      - run: |
          mkdir -p /tmp/dummy
          head -c 1G /dev/urandom > "/tmp/dummy/${CIRCLE_WORKFLOW_JOB_ID}.txt"
      - run: du -Shs /tmp/dummy/
      # we can see that the total available decreases..
      - run: df -h

workflows:
  main:
    jobs:
      - foo:
          context:
            - foo-2
