version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/machine3-linux-tf

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: printenv PATH
      - run: mkdir -p /tmp/throwaway/bin
      - run: touch /tmp/throwaway/bin/nvm_mock
      - run: echo "export PATH='${PATH}://tmp/throwaway/bin" >> $BASH_ENV
      - run: which nvm_mock

workflows:
  main:
    jobs:
      - foo
