version: 2.1

executors:
  machine3-linux:
    machine: true
    resource_class: kelvintaywl-cci/machine3-linux-tf

jobs:
  foo:
    executor: machine3-linux
    steps:
      - run: printenv PATH
      - run: mkdir -p /tmp/throwaway/bin
      - run: |
          cat \<<EOT >> /tmp/throwaway/bin/nvm
          #!/usr/bin/env bash
          echo "mock NVM"
          EOT
          chmod +x /tmp/throwaway/bin/nvm
      - run: echo "export PATH='/tmp/throwaway/bin:$PATH'" >> $BASH_ENV
      - run: printenv PATH
      - run: which nvm

workflows:
  main:
    jobs:
      - foo
