version: 2.1

orbs:
  ruby: circleci/ruby@2.1.0

jobs:
  test:
    machine: true
    # EC2 instance based on Ubuntu Server 22.04 AMI.
    resource_class: kelvintaywl-cci/machine3-ec2-linux2023-tf
    steps:
      - run: lsb_release -a
      - ruby/install:
          # trying to use a more-recent Ruby version
          # based on: https://github.com/rvm/rvm/issues/5254#issuecomment-1259479336
          version: '3.1.4'

workflows:
  main:
    jobs:
      - test
