version: 2.1

jobs:
  pyenv:
    machine: true
    resource_class: kelvintaywl-cci/ec2-linux2023-tf
    environment:
    steps:
      - run: whoami
      - run: echo "echo 'BASH_ENV loaded'" >>  $BASH_ENV
      - run: echo done

workflows:
  main:
    jobs:
      - pyenv
